# Generated by Django 6.0.7 on 2026-07-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='leido',
            field=models.BooleanField(default=False),
        ),
    ]
