# Generated by Django 6.0.7 on 2026-07-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0002_resultado_leido'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='nombre_archivo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
